task-2
NikaOrl/nodejs-aws-fe pull request #1
Opened 2020-10-24 18:49 UTC by NikaOrl

2020-10-25 10:24 UTC, Paul044 commented
Не вижу ссылок на s3/cloudfront, нету serverless.yml

2020-10-25 16:02 UTC, NikaOrl commented
@Paul044 исправила

2020-10-25 17:31 UTC, olekf requested changes

2020-10-25 17:31 UTC, olekf commented on .gitignore
> +.serverless
.serverless already exists in .gitignore

2020-10-25 17:31 UTC, olekf commented on package.json
> +    "deploy:s3": "serverless client deploy --no-config-change --no-policy-change --no-cors-change",
duplicates 'client:deploy' script

2020-10-25 17:31 UTC, olekf commented on package.json
> +    "build:deploy": "npm run build && npm run deploy:s3",
duplicates 'client:build:deploy' script

2020-10-25 17:31 UTC, olekf commented on serverless.yml
> +  runtime: nodejs12.x
no region in configuration, the recommendation was to use eu-west-1 region

2020-10-25 17:52 UTC, olekf commented
Please, follow convention for commit messages: https://docs.rs.school/#/git-convention

2020-10-25 17:55 UTC, olekf commented
Please, follow convention for PR description: https://docs.rs.school/#/stage2?id=Требования-к-pull-request-pr

2020-10-26 08:21 UTC, Paul044 commented
В задании просили 4 ссылки: на s3/cloudfront сделанные вручную, s3/cloudfront сделанные через скрипты

2020-10-26 14:35 UTC, Paul044 commented
> @NikaOrl, В задании просили 4 ссылки: на s3/cloudfront сделанные вручную, s3/cloudfront сделанные через скрипты

появилось объявление, что это не обязательно, всё ок

2020-11-03 18:31 UTC, merged